name: Carrot Deploy
run-name: ${{ github.actor }} is deploying carrot app
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v4'
  
    - run: |
        echo "${{ secrets.CARROT_DEPLOY_KEY }}" > key.json
        gcloud auth activate-service-account --key-file=key.json
        gcloud config set project r-j-magenta-carrot-42069
        gcloud auth list
        gcloud config list
    # - uses: 'google-github-actions/auth@v2'
    #   with:
    #     project_id: 'r-j-magenta-carrot-42069'
    #     credentials_json: '${{ secrets.CARROT_DEPLOY_KEY }}'
